<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	</head>
	<body style='padding:0px; margin:0px;' link="#00fcff" alink="#00a1a9" vlink="#00fcff">
		<table width="100%">
			<tr>
				<td background='<?php echo HOST;?>media/images/email-content/background.png'>
					<div style='margin:0 auto;display:block;width:500px;padding:35px 0px;'>
						<table width='500'>
							<tr>
								<td>
									<img src='<?php echo HOST;?>media/images/email-content/header_confirmacao_email.png' />
								</td>
							</tr>
							<tr>
								<td style='padding: 5px;'>
									<font face='Helvetica, Arial' color='white' size="3">
										<p style='padding: 1px;'>Ol&aacute; <?php echo $this->username;?></p>
										<p style='padding: 1px;'>Uma solicita&ccedil;&atilde;o de troca da sua senha na <a href="<?php echo HOST;?>" style="color:#00a1a9;">Skynerd</a> foi recebida. Para prosseguir, clique no link abaixo:</p>
										<p style='padding: 1px;'><a style="color:#00a1a9;" href='<?php echo $this->link;?>'><?php echo $this->link;?></a></p>
										<p style='padding: 1px;'>Se preferir, copie o link acima e cole no seu navegador favorito.</p>
										<p style='padding: 1px;'>&Eacute; importante lhe dizer que esse link s&oacute; &eacute; v&aacute;lido para hoje!</p>
										<p style='padding: 1px;'>Se n&atilde;o foi você que solicitou a troca da senha, apenas desconsidere este email.</p>
									</font>
								</td>
							</tr>
							<tr>
								<td>
									<a href='http://jovemnerd.ig.com.br'>
										<img src='<?php echo HOST;?>media/images/email-content/footer_email_confirmacao.png' border='0' />
									</a>
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
		</table>
	</body>
</html>