<div id="conteudo" class="ajuda">
	<h2>Ajuda</h2>
	<div>
		<p>Oooopa, nós ainda não temos uma página bacana de ajuda para colocar aqui :(</p>
		<p>Enquanto isso, caso você tenha alguma dificuldade com a Skynerd, você pode entrar em contato conosco pelo email <a href="mailto:bugreport@jovemnerd.com.br">bugreport@jovemnerd.com.br</a> ou pode falar direto comigo, o <a href="<?php echo HOST;?>guicamillo">Arquiteto</a>.</p>
	</div>
</div>

<div id='div-gpt-ad-1373046795970-3' style='width:300px; height:600px;' class="adsense skyscraper publicidade600x300">
	<script type='text/javascript'>
		googletag.cmd.push(function() { googletag.display('div-gpt-ad-1373046795970-3'); });
	</script>
</div>

<div class="clearfix"></div>