<html>
	<head>
		<style>
			*{overflow:hidden;cursor:pointer;}
			form{opacity:0;height:200px;filter:alpha(opacity=0)}
			input{display:block;width:100%;height:100%;filter:alpha(opacity=1);opacity:1;background:#C00;}
		</style>
	</head>
	<body>
		<form action="<?php echo HOST;?>perfil/configuracoes/trocar-avatar" method="post" enctype="multipart/form-data">
			<input type="file" name="new_avatar" id="new_avatar" />
		</form>
	</body>
	<script type="text/javascript" src="<?php echo HOST;?>templates/default/js/jquery.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$("#new_avatar").change(function(){
				var file_extension = ($("#new_avatar").val().split(".")[$("#new_avatar").val().split(".").length - 1]).toString().toLowerCase();;
				var allowed_extensions = ['jpg', 'jpeg', 'png'];
				var valid_extension = $.inArray(file_extension, allowed_extensions);
				
				if(valid_extension === -1){
					alert("Formato de arquivo inválido");
					return false;
				} else {
					$("form").submit()
				}
			});
		})
	</script>
</html>