<div class="conteudo-logout">
	<h2 class="aba">Publicidade</h2>
	<div id='div-gpt-ad-1372386456620-3' style='width:300px; height:600px;' class="publicidadeLogout">
		<script type='text/javascript'>
			googletag.cmd.push(function() { googletag.display('div-gpt-ad-1372386456620-3'); });
		</script>
	</div>
</div>

<div class="conteudo-logout">
	<h2 class="aba">Publicidade</h2>
	<div id='div-gpt-ad-1372386456620-3' style='width:300px; height:600px;' class="publicidadeLogout">
		<script type='text/javascript'>
			googletag.cmd.push(function() { googletag.display('div-gpt-ad-1372386456620-3'); });
		</script>
	</div>
</div>
<img id="nerdinho-logout" src="<?php echo HOST;?>templates/default/images/ilustra-nerdinho-logout.png" />