<div id="conteudo">
	<h2 class="aba esqueci-minha-senha">Esqueci minha senha</h2>
	<p>Ok nerd, vamos redefinir a sua senha...</p>
	<span class="ilustra-nerdinho-esqueci-minha-senha"></span>
	<div class="box-login">
		<h3>seu usuário é <span><?php echo $this->username;?></span>. Preencha os campos abaixo.</h3>
		<form method="post" action="<?php echo HOST;?>esqueci-minha-senha/concluir">
			<fieldset>
				<div>
					<label for="new_password">Nova senha:</label>
					<input type="password" name="new_password" id="new_password" class="primeira-coluna"/>
				</div>
				<div>
					<label for="email">Confirme a nova senha:</label>
					<input type="password" name="new_password_confirm" id="email" class="segunda-coluna" />
				</div>
				<div>
					<input type="submit" value="VAI!" />
				</div>
			</fieldset>
		</form>
	</div>
</div>
<div id='div-gpt-ad-1373046795970-3' style='width:300px; height:600px;' class="adsense skyscraper">
	<script type='text/javascript'>
		googletag.cmd.push(function() { googletag.display('div-gpt-ad-1373046795970-3'); });
	</script>
</div>