<div id="conteudo">
	<h2 class="aba esqueci-minha-senha">Esqueci minha senha</h2>
	<p>Se você já solicitou a troca de senha porém não recebeu nenhum email, adicione uma exceção no seu filtro anti-spam para o domínio jovemnerd.com.br</p>
	<span class="ilustra-nerdinho-esqueci-minha-senha"></span>
	<div class="box-login">
		<h3>Qual dos dois você lembra?</h3>
		<form method="post" action="<?php echo HOST;?>esqueci-minha-senha">
			<fieldset>
				<div>
					<label for="username">Lembro o usuário:</label>
					<input type="text" name="username" id="username" />
				</div>
				<div>
					<label for="email">Lembro o email:</label>
					<input type="text" name="email" id="email" class="segunda-coluna" />
				</div>
				<div>
					<input type="submit" value="VAI!" />
				</div>
			</fieldset>
		</form>
	</div>
</div>
<div id='div-gpt-ad-1373046795970-5' style='width:300px; height:250px;' class="publicidadeLogin">
	<script type='text/javascript'>
		googletag.cmd.push(function() { googletag.display('div-gpt-ad-1373046795970-5'); });
	</script>
</div>
