<div id="conteudo">
	<div id="posts-container" class="single_post">
		<?php echo $this->data->post;?>
	</div>
	<div class="clearfix"></div>
</div>
<div id='div-gpt-ad-1373046795970-3' style='width:300px; height:600px;' class="adsense skyscraper publicidade600x300">
	<script type='text/javascript'>
		googletag.cmd.push(function() { googletag.display('div-gpt-ad-1373046795970-3'); });
	</script>
</div>
<div class="clearfix"></div>